version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=cloud_go_db
      - POSTGRES_USER=cloud_go_user
      - POSTGRES_PASSWORD=cloud_go
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata: