// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO Post (
    title,
    content
) VALUES (
    $1, $2
)
RETURNING id, title, content
`

type CreatePostParams struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreatePostRow struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost, arg.Title, arg.Content)
	var i CreatePostRow
	err := row.Scan(&i.ID, &i.Title, &i.Content)
	return i, err
}

const deletePosts = `-- name: DeletePosts :exec
DELETE FROM Post
WHERE id = $1
`

func (q *Queries) DeletePosts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePosts, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, title, content, created_at FROM Post
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (Post, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, title, content, created_at FROM Post
ORDER BY title
`

func (q *Queries) ListPosts(ctx context.Context) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosts = `-- name: UpdatePosts :one
UPDATE Post
  SET title = $2,
  content = $3
WHERE id = $1
RETURNING id, title, content, created_at
`

type UpdatePostsParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
}

func (q *Queries) UpdatePosts(ctx context.Context, arg UpdatePostsParams) (Post, error) {
	row := q.db.QueryRow(ctx, updatePosts, arg.ID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
